version: '3.1'

services:

  video-concurrents:
    build: ./
    container_name: video-concurrents
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
